//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Context {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Context.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accountant.
        /// </summary>
        internal static string AccountantId {
            get {
                return ResourceManager.GetString("AccountantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên kế toán.
        /// </summary>
        internal static string AccountantName {
            get {
                return ResourceManager.GetString("AccountantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accounting_manager.
        /// </summary>
        internal static string AccountingManagerId {
            get {
                return ResourceManager.GetString("AccountingManagerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trưởng phòng kế toán.
        /// </summary>
        internal static string AccountingManagerName {
            get {
                return ResourceManager.GetString("AccountingManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string AdminId {
            get {
                return ResourceManager.GetString("AdminId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản trị hệ thống.
        /// </summary>
        internal static string AdminName {
            get {
                return ResourceManager.GetString("AdminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chief_technical.
        /// </summary>
        internal static string ChiefTechnicalId {
            get {
                return ResourceManager.GetString("ChiefTechnicalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trưởng phòng kỹ thuật.
        /// </summary>
        internal static string ChiefTechnicalName {
            get {
                return ResourceManager.GetString("ChiefTechnicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manager.
        /// </summary>
        internal static string ManagerId {
            get {
                return ResourceManager.GetString("ManagerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giám đốc.
        /// </summary>
        internal static string ManagerName {
            get {
                return ResourceManager.GetString("ManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qoutation.
        /// </summary>
        internal static string QoutationNamespace {
            get {
                return ResourceManager.GetString("QoutationNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sales_manager.
        /// </summary>
        internal static string SalesManagerId {
            get {
                return ResourceManager.GetString("SalesManagerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trưởng phòng sale.
        /// </summary>
        internal static string SalesManagerName {
            get {
                return ResourceManager.GetString("SalesManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sale_staff.
        /// </summary>
        internal static string SaleStaffId {
            get {
                return ResourceManager.GetString("SaleStaffId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên sale.
        /// </summary>
        internal static string SaleStaffName {
            get {
                return ResourceManager.GetString("SaleStaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string TaskNamespace {
            get {
                return ResourceManager.GetString("TaskNamespace", resourceCulture);
            }
        }
    }
}
